import React from 'react';
import { Save, ArrowDownCircle, Truck, Package, Plus, Calendar, Search, Filter, X } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { TableAction } from '@/components/ui/TableAction';

export function StockIn() {
  return (
    <div className="space-y-8 animate-fade-in p-6 pb-20 bg-slate-50 min-h-screen">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-800 flex items-center gap-2"><ArrowDownCircle className="text-emerald-600" /> Entrada de Estoque</h1><p className="text-slate-500">Registre recebimento de mercadorias.</p></div></div>
      
      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden"><div className="p-6 border-b border-slate-100 flex items-center gap-3"><div className="p-2 bg-emerald-50 text-emerald-600 rounded-lg"><Plus size={20} /></div><h2 className="text-lg font-bold text-slate-800">Nova Entrada</h2></div><div className="p-6 space-y-6"><div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div className="flex items-center justify-between px-4 py-3 border border-slate-300 rounded-lg bg-slate-50"><div className="flex items-center gap-3 text-slate-500 italic"><Truck size={18} /> <span>Fornecedor...</span></div><Button variant="soft" size="sm">BUSCAR</Button></div><div className="flex items-center justify-between px-4 py-3 border border-slate-300 rounded-lg bg-slate-50"><div className="flex items-center gap-3 text-slate-500 italic"><Package size={18} /> <span>Produto...</span></div><Button variant="soft" size="sm">BUSCAR</Button></div></div><div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div><label className="block text-xs font-bold text-slate-500 uppercase mb-2">Quantidade</label><input type="number" className="w-full px-4 py-2.5 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-emerald-500" /></div><div><label className="block text-xs font-bold text-slate-500 uppercase mb-2">Preço Custo</label><input type="number" className="w-full px-4 py-2.5 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-emerald-500" /></div></div></div>
      {/* CORRIGIDO: Agora alinha à direita e tem tamanho normal, igual aos cadastros */}
      <div className="p-4 bg-slate-50 border-t border-slate-200 flex justify-end"><Button variant="primary" icon={Save}>REGISTRAR ENTRADA</Button></div></div>
      
      {/* Tabela... */}
      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden"><div className="p-6 border-b border-slate-200"><h2 className="text-lg font-bold text-slate-800 mb-6">Entradas Recentes</h2><div className="bg-slate-50 p-6 rounded-lg border border-slate-200 space-y-4"><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4"><div className="lg:col-span-2"><label className="text-xs font-bold text-slate-500 uppercase">Buscar</label><div className="relative mt-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} /><input type="text" className="w-full pl-10 pr-4 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-blue-500 bg-white" placeholder="Produto ou Fornecedor..." /></div></div></div><div className="flex gap-2 pt-2"><Button variant="soft" size="sm" icon={Filter}>FILTRAR</Button><Button variant="outline" size="sm" icon={X}>LIMPAR</Button></div></div></div><div className="overflow-x-auto"><table className="w-full text-left border-collapse min-w-[700px]"><thead className="bg-slate-50 text-slate-600 text-xs uppercase font-bold border-b border-slate-200"><tr><th className="p-4">Produto</th><th className="p-4">Fornecedor</th><th className="p-4 text-center">Qtd.</th><th className="p-4 text-center">Data</th><th className="p-4 text-right">Ações</th></tr></thead><tbody className="text-sm text-slate-600"><tr className="hover:bg-slate-50 border-b border-slate-100 last:border-0"><td className="p-4 font-bold text-slate-800">Câmara de ar</td><td className="p-4 text-slate-500 italic">SEM FORNECEDOR</td><td className="p-4 text-center font-bold text-emerald-600">1</td><td className="p-4 text-center">17/12</td><td className="p-4 text-right"><div className="flex justify-end gap-2"><TableAction variant="edit" /><TableAction variant="delete" /></div></td></tr></tbody></table></div></div>
    </div>
  );
}