import React from 'react';
import { Save, Search, Filter, X, ArrowUpCircle, User, Plus, ClipboardList, Calendar } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { TableAction } from '@/components/ui/TableAction';

export function StockOut() {
  return (
    <div className="space-y-8 animate-fade-in p-6 pb-20 bg-slate-50 min-h-screen">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-800 flex items-center gap-2"><ArrowUpCircle className="text-blue-600" /> Saída de Material</h1><p className="text-slate-500">Registre consumo ou retirada.</p></div></div>
      
      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden"><div className="p-6 border-b border-slate-100 flex items-center gap-3"><div className="p-2 bg-blue-50 text-blue-600 rounded-lg"><ClipboardList size={20} /></div><h2 className="text-lg font-bold text-slate-800">Nova Saída</h2></div><div className="p-6 space-y-6"><div className="flex items-center justify-between w-full px-4 py-3 border border-slate-300 rounded-lg bg-slate-50"><div className="flex items-center gap-3 text-slate-500 italic"><User size={18} /> <span>Funcionário...</span></div><Button variant="soft" size="sm">BUSCAR</Button></div><div className="border-x border-b border-slate-200 rounded-b-lg bg-slate-50 p-8 flex flex-col items-center justify-center text-slate-400"><p className="italic mb-4">Nenhum produto na lista.</p><Button variant="soft" icon={Plus}>ADICIONAR PRODUTO</Button></div></div>
      {/* CORRIGIDO: Agora alinha à direita e tem tamanho normal, igual aos cadastros */}
      <div className="p-4 bg-slate-50 border-t border-slate-200 flex justify-end"><Button variant="primary" icon={Save}>REGISTRAR SAÍDA</Button></div></div>
      
      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden"><div className="p-6 border-b border-slate-200"><h2 className="text-lg font-bold text-slate-800 mb-6">Histórico de Saídas</h2><div className="bg-slate-50 p-6 rounded-lg border border-slate-200 flex flex-col md:flex-row gap-4 items-end"><div className="flex-1 w-full"><label className="text-xs font-bold text-slate-500 uppercase">Buscar</label><div className="relative mt-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} /><input type="text" className="w-full pl-10 pr-4 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-blue-500 bg-white" placeholder="Produto ou Funcionário..." /></div></div><div className="flex gap-2 w-full md:w-auto"><Button variant="soft" icon={Filter}>FILTRAR</Button><Button variant="outline" icon={X}>LIMPAR</Button></div></div></div><div className="overflow-x-auto"><table className="w-full text-left border-collapse min-w-[900px]"><thead className="bg-slate-50 text-slate-600 text-xs uppercase font-bold border-b border-slate-200"><tr><th className="p-4">Produto</th><th className="p-4">Funcionário</th><th className="p-4 text-center">Qtd.</th><th className="p-4 text-center">Data</th><th className="p-4 text-center">Devolvível</th><th className="p-4 text-right">Ações</th></tr></thead><tbody className="text-sm text-slate-600"><tr className="hover:bg-slate-50 border-b border-slate-100 last:border-0"><td className="p-4 font-bold text-slate-800">Luva Curta</td><td className="p-4">RAIMUNDO VELOSO</td><td className="p-4 text-center font-bold text-blue-600">1</td><td className="p-4 text-center">18/12</td><td className="p-4 text-center">Não</td><td className="p-4 text-right"><div className="flex justify-end gap-2"><TableAction variant="edit" /><TableAction variant="delete" /></div></td></tr></tbody></table></div></div>
    </div>
  );
}